# file: roles/mysql/tasks/configure.yml

- name: Set MySQL root password
  mysql_user: name=root 
              host={{ item }} 
              password={{ mysql_root_password }} priv=*.*:ALL,GRANT
              login_user=root
              login_password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - localhost
