# file: roles/httpd/tasks/packages.yml

- name: Install MySQL packages
  yum: pkg={{ item }}
  with_items:
    - mysql
    - mysql-server
    - mysql-devel
    - MySQL-python

- name: Start mysql service
  service: name=mysqld state=started enabled=yes
