# file roles/php/tasks/packages.yml

- name: Install PHP packages
  sudo: yes
  yum: pkg={{ item }} state=present
  with_items:
    - php
    - php-mysql
    - php-common
    - php-gd
    - php-mbstring
    - php-devel
    - php-xml
  notify:
  - restart httpd
